version: '3.9'
services:
  xtradb-master:
    container_name: xtradb-master
    image: 'percona/percona-xtradb-cluster:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - CLUSTER_NAME=fsn-xtradb-cluster
    ports:
      - 3306:3306
      - 4567:4567
      - 4568:4568
      - 4444:4444
    expose:
      - 3306
      - 33060
      - 4567
      - 4568
      - 4444
    volumes:
      - ./config:/etc/percona-xtradb-cluster.conf.d
      - ./cert:/cert
      - ./data-master:/var/lib/mysql
      # - ./nothing:/docker-entrypoint-initdb.d/nothing.sh
      # - ./grastate.dat:/var/lib/mysql/grastate.dat
    # restart: always
    # command: ["/bin/sh", "-c", "sleep 5; mysqld"]
    networks:
      - fsn-net
    # restart: always
  xtradb-slave1:
    container_name: xtradb-slave1
    depends_on:
      - xtradb-master
    image: 'percona/percona-xtradb-cluster:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - CLUSTER_NAME=fsn-xtradb-cluster
      - CLUSTER_JOIN=xtradb-master
    expose:
      - 3306
      - 33060
      - 4567
      - 4568
      - 4444
    volumes:
      - ./config:/etc/percona-xtradb-cluster.conf.d
      - ./cert:/cert
      - ./data-slave1:/var/lib/mysql
      # - ./nothing:/docker-entrypoint-initdb.d/nothing.sh
    # restart: always
    command: ["/bin/sh", "-c", "sleep 25; mysqld"]
    networks:
      - fsn-net
  xtradb-slave2:
    container_name: xtradb-slave2
    depends_on:
      - xtradb-master
    image: 'percona/percona-xtradb-cluster:latest'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - CLUSTER_NAME=fsn-xtradb-cluster
      - CLUSTER_JOIN=xtradb-master
    expose:
      - 3306
      - 33060
      - 4567
      - 4568
      - 4444
    volumes:
      - ./config:/etc/percona-xtradb-cluster.conf.d
      - ./cert:/cert
      - ./data-slave2:/var/lib/mysql
      # - ./nothing:/docker-entrypoint-initdb.d/nothing.sh
    # restart: always
    command: ["/bin/sh", "-c", "sleep 25; mysqld"]
    networks:
      - fsn-net
networks:
  fsn-net:
